wandb_version: 1

codebook_groups:
  desc: null
  value: 32,32,32
language:
  desc: null
  value: eng
hidden_size:
  desc: null
  value: 256
num_heads:
  desc: null
  value: 4
num_layers:
  desc: null
  value: 6
lr:
  desc: null
  value: 0.0001
rho:
  desc: null
  value: 0.2
alpha:
  desc: null
  value: 0.0
ema_decay:
  desc: null
  value: 0.99
vq_loss_weight:
  desc: null
  value: 0.5
orthogonal_loss_weight:
  desc: null
  value: 0.0
attention_dropout:
  desc: null
  value: 0.3
encoder_dropout:
  desc: null
  value: 0.3
codebook_dropout:
  desc: null
  value: 0.3
decoder_dropout:
  desc: null
  value: 0.3
num_steps:
  desc: null
  value: 15000
steps_per_epoch:
  desc: null
  value: 1000
num_epochs:
  desc: null
  value: 15
batch_size:
  desc: null
  value: 2
max_length:
  desc: null
  value: 20
seed:
  desc: null
  value: 42
weight_decay:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1711563578.140494
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.8.18
      5: 0.16.3
      8:
      - 2
      - 5
      13: linux-x86_64
